# Blockchain by example


version: '2'

volumes:
  orderer.dash.com:
  peer0.org1.dash.com:
  peer1.org1.dash.com:
  peer0.org2.dash.com:
  peer1.org2.dash.com:
  peer0.org3.dash.com:
  peer1.org3.dash.com:
  kafka0.dash.com:
  kafka1.dash.com:
  kafka2.dash.com:
  kafka3.dash.com:
  zookeeper0:
  zookeeper1:
  zookeeper2:

networks:
  network:

services:
  kafka0:
    extends:
      file: base/docker-compose-mq.yaml
      service: kafka0
    container_name: kafka0.dash.com
    networks:
      - network

  kafka1:
    extends:
      file: base/docker-compose-mq.yaml
      service: kafka1
    container_name: kafka1.dash.com
    networks:
      - network
  
  kafka2:
    extends:
      file: base/docker-compose-mq.yaml
      service: kafka2
    container_name: kafka2.dash.com
    networks:
      - network
  
  kafka3:
    extends:
      file: base/docker-compose-mq.yaml
      service: kafka3
    container_name: kafka3.dash.com
    networks:
      - network

  zookeeper0:
    extends:
      file: base/docker-compose-mq.yaml
      service: zookeeper0
    container_name: zookeeper0
    networks:
      - network

  zookeeper1:
    extends:
      file: base/docker-compose-mq.yaml
      service: zookeeper1
    container_name: zookeeper1
    networks:
      - network

  zookeeper2:
    extends:
      file: base/docker-compose-mq.yaml
      service: zookeeper2
    container_name: zookeeper2
    networks:
      - network
  orderer.supply.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.supply.com
    container_name: orderer.supply.com
    networks:
      - network

  peer0.org1.supply.com:
    container_name: peer0.org1.supply.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.supply.com
    networks:
      - network

  peer1.org1.supply.com:
    container_name: peer1.org1.supply.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.supply.com
    networks:
      - network

  peer0.org2.supply.com:
    container_name: peer0.org2.supply.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.supply.com
    networks:
      - network

  peer1.org2.supply.com:
    container_name: peer1.org2.supply.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.supply.com
    networks:
      - network

  peer0.org3.supply.com:
    container_name: peer0.org3.supply.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org3.supply.com
    networks:
      - network

  peer1.org3.supply.com:
    container_name: peer1.org3.supply.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org3.supply.com
    networks:
      - network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.3
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_network
      #- CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_LEVEL=INFO
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.supply.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.supply.com/peers/peer0.org1.supply.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.supply.com/peers/peer0.org1.supply.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.supply.com/peers/peer0.org1.supply.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.supply.com/users/Admin@org1.supply.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.supply.com
      - peer0.org1.supply.com
      - peer1.org1.supply.com
      - peer0.org2.supply.com
      - peer1.org2.supply.com
      - peer0.org3.supply.com
      - peer1.org3.supply.com
    networks:
      - network
